---
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: apache2 listen on port {{ http_port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
  notify:
    - restart apache

- name: apache2 virtualhost on port {{ http_port }}
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
  notify:
    - restart apache

- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
    - restart apache

- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php7.0 state=present
  notify:
    - restart apache

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache

- name:  install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

