---
# - name: Install Lib Mysql Client
#   apt: pkg=libmysqlclient-dev state=latest

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: Make my cache tree readable
  file: dest=/var/www/html/symfony/current/var owner=www-data mode=0777 recurse=yes

- name: Change owner
  file: dest=/var/www/html/symfony/releases owner=www-data

- name: Set a line of DocumentRoot
  lineinfile: dest=/etc/apache2/sites-enabled/000-default state=absent regexp="^DocumentRoot /var/www/html/symfony/current/web/app_dev.php$"

# - name: apache2 virtualhost on port 8081
#   lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present

# - name: Install the MySQL packages
#   apt: name={{ item }} state=installed update_cache=yes
#   with_items:
#     - mysql-server
#     - mysql-client
#     - python-mysqldb
#     - libmysqlclient-dev

# - name: Update MySQL root password for all root accounts
#   mysql_user: name=root host={{ item }} password="djscrave" state=present
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost

# - name: Copy the root credentials as .my.cnf file
#   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

# - name: Ensure Anonymous user(s) are not in the database
#   mysql_user: name='' host={{ item }} state=absent
#   with_items:
#     - localhost
#     - "{{ ansible_hostname }}"

# - name: Remove the test database
#   mysql_db: name=test state=absent
#   notify:
#     - Restart MySQL
